export default [
  {
    id: 44,
    title: '라일락',
    img: 'https://musicmeta-phinf.pstatic.net/album/005/211/5211473.jpg?type=r360Fll&v=20210326102709',
    date: '2021.03.25',
    type: 'studio',
    trackList: [
      {
        no: 1,
        name: '라일락',
        is_title: 0,
        lyrics: ['아이유'],
        composed: ['임수호', 'Dr.JO', '옹킴', 'N!ko'],
        arranged: ['임수호', '옹킴', 'N!ko'],
      },
      {
        no: 2,
        name: 'Flu',
        is_title: 0,
        lyrics: ['아이유'],
        composed: [
          '라이언 전',
          'Martin Coogan',
          'Madilyn Bailey',
          'Zacchariah Palmer',
          'London Jackson',
          'Jacob Chatelain',
        ],
        arranged: ['Jacob Chatelain', 'London Jackson', '라이언 전'],
      },
      {
        no: 3,
        name: 'Coin',
        is_title: 1,
        lyrics: ['아이유'],
        composed: ['Poptime', 'Kako', '아이유'],
        arranged: ['Poptime'],
      },
      {
        no: 4,
        name: '봄 안녕 봄',
        is_title: 0,
        lyrics: ['아이유'],
        composed: ['나얼'],
        arranged: ['강화성'],
      },
      {
        no: 5,
        name: 'Celebrity',
        is_title: 1,
        lyrics: ['아이유'],
        composed: [
          '라이언 전',
          'Jeppe London Bilsby',
          'Lauritz Emil Christiansen',
          '아이유',
          'Chloe Latimer',
          'Celine Svanback',
        ],
        arranged: ['eppe London Bilsby', 'Lauritz Emil Christiansen', '라이언 전'],
      },
      {
        no: 6,
        name: '돌림노래 (Feat. DEAN)',
        is_title: 0,
        lyrics: ['아이유', 'Deanfluenza'],
        composed: ['박우상', 'JUNNY', 'Deanfluenza', 'jane'],
        arranged: ['박우상'],
      },
      {
        no: 7,
        name: '빈 컵 (Empty Cup)',
        is_title: 0,
        lyrics: ['아이유'],
        composed: ['WOOGIE', 'PENOMECO'],
        arranged: ['WOOGIE'],
      },
      {
        no: 8,
        name: '아이와 나의 바다',
        is_title: 0,
        lyrics: ['아이유'],
        composed: ['제휘', '김희원'],
        arranged: ['제휘'],
      },
      {
        no: 9,
        name: '어푸 (Ah puh)',
        is_title: 0,
        lyrics: ['아이유', '이찬혁'],
        composed: ['이찬혁', 'PEEJAY'],
        arranged: ['PEEJAY'],
      },
      {
        no: 10,
        name: '에필로그',
        is_title: 0,
        lyrics: ['아이유'],
        composed: ['심은지', 'SUMIN', '김수영', '임금비'],
        arranged: ['심은지', '김수영'],
      },
    ],
  },

  {
    id: 43,
    title: 'I-LAND Part 1 Signal Song',
    img: 'https://musicmeta-phinf.pstatic.net/album/004/600/4600362.jpg?type=r360Fll&amp;v=20210303145028',
    date: '2020.06.19',
    type: 'ost',
    trackList: [
      {
        no: 1,
        name: 'Into the I-LAND',
        is_title: 1,
        lyrics: [
          'Wonderkid',
          'Melanie Joy Fontana',
          'Michel “Lindgren” Schulz',
          '"hitman"bang',
          'danke',
          '이스란',
          '탐쓴 (TOMSSON)',
          '송재경',
        ],
        composed: [
          'Wonderkid',
          'Melanie Joy Fontana',
          'Michel “Lindgren” Schulz',
          '"hitman"bang',
          'danke',
          '이스란',
          '탐쓴 (TOMSSON)',
          '송재경',
        ],
        arranged: [],
      },
    ],
  },
  {
    id: 42,
    title: '에잇',
    img: 'https://musicmeta-phinf.pstatic.net/album/004/550/4550593.jpg?type=r360Fll&v=20210303143526',
    date: '2020.05.06',
    type: 'digital single',
    trackList: [
      {
        no: 1,
        name: '에잇(Prod.&Feat. SUGA of BTS)',
        is_title: 1,
        lyrics: ['아이유', 'SUGA'],
        composed: ['SUGA', '아이유', 'EL CAPITXN'],
        arranged: ['SUGA', 'EL CAPITXN', '아이유'],
      },
    ],
  },
  {
    id: 41,
    title: '사랑의 불시착 OST Part 11',
    img: 'https://musicmeta-phinf.pstatic.net/album/004/448/4448098.jpg?type=r360Fll&v=20210303130024',
    date: '2020.2.15',
    type: 'ost',
    trackList: [
      {
        no: 1,
        name: '마음을 드려요',
        is_title: 1,
        lyrics: ['남혜승', '박진호'],
        composed: ['남혜승', '박진호'],
        arranged: ['남혜승', '박진호'],
      },
    ],
  },
  {
    id: 40,
    title: '첫 겨울 이니까',
    img: 'https://musicmeta-phinf.pstatic.net/album/003/719/3719484.jpg?type=r360Fll&v=20210303124023',
    date: '2019.12.9',
    type: 'digital single',
    trackList: [
      {
        no: 1,
        name: '첫 겨울이니까 (성시경&아이유)',
        is_title: 1,
        lyrics: ['이규호'],
        composed: ['이규호'],
        arranged: ['강화성'],
      },
    ],
  },
  {
    id: 39,
    title: 'Love poem',
    img: 'https://musicmeta-phinf.pstatic.net/album/003/399/3399860.jpg?type=r360Fll&v=20210530010527',
    date: '2019.11.18',
    type: 'mini',
    trackList: [
      {
        no: 1,
        name: 'unlucky',
        is_title: 0,
        lyrics: ['제휘'],
        composed: ['아이유'],
        arranged: ['제휘'],
      },
      {
        no: 2,
        name: '그 사람',
        is_title: 0,
        lyrics: ['아이유'],
        composed: ['아이유'],
        arranged: ['적재'],
      },
      {
        no: 3,
        name: 'Blueming',
        is_title: 1,
        lyrics: ['이종훈', '이채규', '아이유'],
        composed: ['아이유'],
        arranged: ['이종훈', '이채규'],
      },
      {
        no: 4,
        name: '시간의 바깥',
        is_title: 0,
        lyrics: ['이민수'],
        composed: ['아이유'],
        arranged: ['이민수'],
      },
      {
        no: 5,
        name: '자장가',
        is_title: 0,
        lyrics: ['김희원'],
        composed: ['아이유'],
        arranged: ['홍소진'],
      },
      {
        no: 6,
        name: 'Love poem',
        is_title: 1,
        lyrics: ['이종훈'],
        composed: ['아이유'],
        arranged: ['홍소진', '적재'],
      },
    ],
  },
]
